# Generated by Django 4.2.17 on 2025-01-16 11:51

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_community_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default='Describe Event'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
