# Generated by Django 4.2.17 on 2025-01-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_course_description_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_on',
        ),
    ]
