# Generated by Django 4.2.17 on 2025-01-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='author',
        ),
    ]
